version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase as $USER on $PWD
      - curl -s "https://get.sdkman.io" | bash
      - source "/root/.sdkman/bin/sdkman-init.sh" && sdk install java && sdk install maven
      - pip install pytest pytest-html
  build:
    commands:
      - echo Entered the build phase...
# Java
      - mkdir -p target/reports/java/
      - mvn --no-transfer-progress -Dmaven.test.failure.ignore=true --fail-at-end test
      - mvn --no-transfer-progress surefire-report:report  -Daggregate=true
      - mvn --no-transfer-progress site -DgenerateReports=false
      - mv target/site/* target/reports/java/
# Python
      - pushd rom-to-dec-py && pytest --html=../target/reports/python/rom-to-dec.html --self-contained-html && popd
#      - pushd bcoef && pytest --html=../target/reports/python/bcoef.html --self-contained-html && popd
# Publish reports 
      - pwd
      - ls -liah
      - aws s3 sync target/reports/ s3://codinginterviews.caravana.cloud/ --delete
cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.sdkman/**/*'
